name: ca
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - black
  - pip
  - pip:
    - statsmodels

